# Linked echo project: https://audpduzramwavabcrqws.supabase.co
project_id = "audpduzramwavabcrqws"

[api]
enabled = true
port = 54321
schemas = ["public"]
extra_search_path = ["public"]
max_rows = 1000

[db]
port = 54322
major_version = 17

[db.migrations]
enabled = true
schema_paths = []

[auth.third_party.clerk]
enabled = true
domain = "helped-pipefish-6125.clerk.accounts.dev"
